import type { Metadata } from 'next';
import { Inter, Bricolage_Grotesque } from 'next/font/google';
import './globals.css';
// import NavBar from "./components/NavBar";
import { Footer } from './components/Footer';

const inter = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
});

const bricolageGrotesque = Bricolage_Grotesque({
    variable: '--font-bricolage-grotesque',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://fonts.googleapis.com/css2?family=Sherika:wght@400;500&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body
                className={`${inter.variable} ${bricolageGrotesque.variable} antialiased`}
            >
                {children}
                <Footer />
            </body>
        </html>
    );
}
